server {
    listen 80;                      # 1. "Слухай запити, які приходять на 80-й порт"
    server_name localhost;          # 2. "Приймай звернення за адресою localhost"

    location / {
        root /usr/share/nginx/html; # 3. "Усі файли сайту лежать у цій папці"
        index index.html;           # 4. "Головний файл — це index.html"
        try_files $uri $uri/ /index.html; # 5. "Якщо користувач щось шукає і не знаходить — все одно відкрий йому index.html"
    }
}